# Generated by Django 5.2.5 on 2025-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['time_create']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['time_create'], name='star_recipe_time_cr_c93fea_idx'),
        ),
    ]
