# Generated by Django 5.2.5 on 2025-08-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_alter_recipe_options_recipe_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
