# Generated by Django 5.2.5 on 2025-08-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0004_category_recipe_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='star.category'),
        ),
    ]
