# Generated by Django 5.2.5 on 2025-08-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0005_alter_recipe_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-time_create'], 'verbose_name': 'Лучшие рецепты', 'verbose_name_plural': 'Лучшие рецепты'},
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='star_recipe_time_cr_c93fea_idx',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='star.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='effect',
            field=models.CharField(max_length=255, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='game',
            field=models.CharField(max_length=255, verbose_name='Название игры'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation',
            field=models.CharField(max_length=255, verbose_name='Способ приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-time_create'], name='star_recipe_time_cr_042cd8_idx'),
        ),
    ]
